# Generated by Django 3.1.4 on 2020-12-23 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_catpost'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CatPost',
        ),
    ]
