# Generated by Django 3.1.4 on 2020-12-23 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NewCatPost',
            new_name='CatPost',
        ),
    ]
