# Generated by Django 3.1.4 on 2020-12-24 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20201223_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catpost',
            name='image',
            field=models.URLField(),
        ),
    ]
